version: "3.9"

services:
  db:
    restart: always
    container_name: postgreSQL
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - shared_data:/app/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - eniac

  backend:
    build: .
    image: 33zahra/eniac-backend:base_image
    container_name: backend
    volumes:
      - .:/app
      - media_volume:/app/media
      - shared_data:/app/data/
      - static_volume:/app/static
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - name=value
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    command: 
      - ./docker-entrypoint.sh
    ports:
      - '8000:8000'
    expose:
      - '8000' 
    links:
      - db:db
    networks:
      - eniac


networks:
  eniac:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
  shared_data:
  static_volume:
