FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv supervisor build-essential python3-dev libpq-dev  redis-server

ARG USER=root
RUN groupadd app && useradd -g app app

USER $USER

RUN python3 -m venv eniac_venv

WORKDIR /app

# install dependencies    
COPY requirements.txt /app/

RUN /eniac_venv/bin/pip install -r requirements.txt

ENV VIRTUAL_ENV=/eniac_venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y \
    netcat \
    ffmpeg 
    
# Copy project
COPY . /app/

COPY deploy deploy

COPY deploy/daphne.conf /etc/supervisor/conf.d/daphne.conf

RUN mkdir /logs

#RUN chmod +x docker-entrypoint.sh 
#RUN chmod +x wait-for.sh
# COPY data.sql data/
EXPOSE 8000
EXPOSE 8001


RUN chmod 755 /app/deploy/start_daphne.sh
RUN sed -i 's/\r$//' /app/deploy/start_daphne.sh

# CMD [ "python" , "manage.py" , "runserver" ]

