# Generated by Django 5.0.3 on 2024-12-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychiatrist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
