# Generated by Django 5.0.3 on 2024-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
